# DANS LA VERSION PROCHAINE
buttons:
   # Si vous modifiez des valeurs, il faudra refaire spawner les bouttons.
   start:
      name: "&aDébuter le vote."
      block: HARD_CLAY
      # Si il n'y a pas d'id, mettre zero.
      id: 5
   stop:
      name: "&cTerminer le vote."
      block: HARD_CLAY
      # Si il n'y a pas d'id, mettre zero.
      id: 14
